"use client";

import { useEffect, useRef, useState } from "react";

import { useToast } from "@/components/toast/ToastProvider";

interface OffspringProfilePanelProps {
  petAId: string;
  petBId: string;
  petAName: string;
  petBName: string;
}

interface GallerySide {
  petName: string;
  breedName: string;
  petPhoto: string | null;
  breedHero: string | null;
  references: { url: string; caption: string }[];
}
interface GalleryResponse {
  parentA: GallerySide;
  parentB: GallerySide;
  mixPhotos: { url: string; caption: string }[];
}

/**
 * The holistic offspring-profile prediction panel — coat colors, size,
 * temperament, appearance, training notes. Streams the AI text from
 * /api/predict/offspring, then loads a real-photo gallery from
 * /api/predict/offspring/images so visitors see actual dogs of each
 * parent breed (not AI-generated previews).
 */
export function OffspringProfilePanel({
  petAId,
  petBId,
  petAName,
  petBName,
}: OffspringProfilePanelProps) {
  const toast = useToast();
  const [text, setText] = useState("");
  const [streaming, setStreaming] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [gallery, setGallery] = useState<GalleryResponse | null>(null);
  const startedRef = useRef(false);

  useEffect(() => {
    // Effects run twice in dev under React Strict Mode; gate via ref.
    if (startedRef.current) return;
    startedRef.current = true;
    void runPrediction();
    void loadGallery();

    async function loadGallery() {
      try {
        const r = await fetch("/api/predict/offspring/images", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ petAId, petBId }),
        });
        if (!r.ok) return;
        const data = (await r.json()) as GalleryResponse;
        setGallery(data);
      } catch {
        /* gallery is decorative — failing silently is fine */
      }
    }

    async function runPrediction() {
      try {
        const r = await fetch("/api/predict/offspring", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ petAId, petBId }),
        });
        if (!r.ok || !r.body) {
          const data = await r.json().catch(() => ({}));
          throw new Error(
            (data as { error?: string }).error ?? "Prediction request failed",
          );
        }
        const reader = r.body.getReader();
        const decoder = new TextDecoder();
        let acc = "";
        // eslint-disable-next-line no-constant-condition
        while (true) {
          const { value, done } = await reader.read();
          if (done) break;
          acc += decoder.decode(value, { stream: true });
          setText(acc);
        }
      } catch (err) {
        const message = (err as Error).message;
        setError(message);
        toast.error("Couldn't generate the offspring profile", message);
      } finally {
        setStreaming(false);
      }
    }
  }, [petAId, petBId, toast]);

  return (
    <section className="mt-12">
      <header className="mb-5 max-w-2xl">
        <p className="eyebrow">AI offspring profile</p>
        <h2
          className="mt-3 leading-tight text-dark"
          style={{
            fontFamily: "var(--font-playfair, Georgia, serif)",
            fontWeight: 900,
            fontSize: "clamp(1.75rem, 4vw, 2.5rem)",
          }}
        >
          What the litter will likely look like
        </h2>
        <p className="mt-2 text-sm text-dark-muted leading-relaxed">
          A holistic prediction of {petAName} × {petBName}&apos;s puppies — coat,
          size, temperament, and any health considerations from the parents&apos;
          DNA records. Generated by an AI model grounded in both parents&apos;
          breed reference + trait data; not a clinical recommendation.
        </p>
      </header>

      {gallery && <ParentBreedGallery gallery={gallery} />}

      {gallery && gallery.mixPhotos.length > 0 && (
        <MixBreedGallery
          mixPhotos={gallery.mixPhotos}
          breedA={gallery.parentA.breedName}
          breedB={gallery.parentB.breedName}
        />
      )}

      <article className="rounded-3xl border border-sand bg-surface p-6 shadow-card md:p-8">
        {streaming && text.length === 0 ? (
          <div className="flex items-center gap-2 text-sm text-dark-muted">
            <Dots />
            <span>Analyzing {petAName} and {petBName}&apos;s genetic profiles…</span>
          </div>
        ) : error ? (
          <p className="text-sm text-dark-muted">
            We couldn&apos;t generate the prediction right now. {error}
          </p>
        ) : (
          <MarkdownPreview text={text} />
        )}
        {streaming && text.length > 0 && (
          <div className="mt-3 flex items-center gap-2 text-[11px] text-dark-muted">
            <Dots />
            <span>Still writing…</span>
          </div>
        )}
      </article>
    </section>
  );
}

/* ─── Real-photo gallery ─────────────────────────────────────────────── */

/**
 * Renders a small gallery of REAL photographs of each parent breed,
 * with a prominent disclaimer that offspring will combine parent
 * traits in unpredictable ways. Deliberately not AI-generated — every
 * photo here is a real licensed dog photo (Unsplash + the seeded pet
 * photos).
 */
function ParentBreedGallery({ gallery }: { gallery: GalleryResponse }) {
  function sideCards(side: GallerySide) {
    const out: { url: string; caption: string }[] = [];
    if (side.petPhoto) {
      out.push({ url: side.petPhoto, caption: `${side.petName} — ${side.breedName}` });
    }
    if (side.breedHero && side.breedHero !== side.petPhoto) {
      out.push({ url: side.breedHero, caption: `Typical ${side.breedName}` });
    }
    for (const r of side.references) {
      if (out.length >= 3) break;
      out.push(r);
    }
    return out.slice(0, 3);
  }

  const aCards = sideCards(gallery.parentA);
  const bCards = sideCards(gallery.parentB);

  return (
    <section className="mb-6 rounded-3xl border border-sand bg-cream/40 p-5 md:p-6">
      <div className="mb-4 flex flex-wrap items-baseline justify-between gap-3">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-terracotta">
            Real photos · parent breeds
          </p>
          <h3
            className="mt-1 leading-tight text-dark"
            style={{
              fontFamily: "var(--font-playfair, Georgia, serif)",
              fontWeight: 800,
              fontSize: "1.25rem",
            }}
          >
            What the parent breeds look like
          </h3>
        </div>
        <p className="max-w-md text-[12px] text-dark-muted leading-relaxed">
          Actual licensed photographs of the two parent breeds — not AI
          generations. The litter will combine traits from both parents in
          varied, individually unique ways.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
        <SideColumn
          title={`${gallery.parentA.petName} — ${gallery.parentA.breedName}`}
          cards={aCards}
        />
        <SideColumn
          title={`${gallery.parentB.petName} — ${gallery.parentB.breedName}`}
          cards={bCards}
        />
      </div>

      <p className="mt-5 rounded-2xl border border-sand bg-surface/70 px-4 py-3 text-[12px] leading-relaxed text-dark-muted">
        <strong className="text-dark">Real photos, not predictions.</strong>{" "}
        These are reference photographs of each parent&apos;s breed — they
        show typical examples, not the actual offspring of this specific
        pairing. Real litters vary significantly: puppies can take after
        either parent, show intermediate features, or surface unexpected
        coat patterns. Treat these as a visual reference for the genetic
        starting point, not a guarantee of how the puppies will look.
      </p>
    </section>
  );
}

function SideColumn({
  title,
  cards,
}: {
  title: string;
  cards: { url: string; caption: string }[];
}) {
  return (
    <div>
      <p className="mb-3 text-[11px] font-semibold uppercase tracking-wider text-dark-muted">
        {title}
      </p>
      <div className="grid grid-cols-3 gap-2">
        {cards.map((c, i) => (
          <figure key={`${c.url}-${i}`} className="overflow-hidden rounded-2xl">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={c.url}
              alt={c.caption}
              className="aspect-square w-full object-cover transition-transform hover:scale-[1.03]"
              loading="lazy"
            />
            <figcaption className="mt-1 truncate text-[10px] text-dark-muted">
              {c.caption}
            </figcaption>
          </figure>
        ))}
      </div>
    </div>
  );
}

/**
 * Renders REAL photos of actual mix-breed dogs of this specific cross
 * (e.g. German Shepherd × American Pit Bull Terrier). Only shown when
 * we have a curated set for the pair — better to hide the section
 * than to show generic stock photos.
 */
function MixBreedGallery({
  mixPhotos,
  breedA,
  breedB,
}: {
  mixPhotos: { url: string; caption: string }[];
  breedA: string;
  breedB: string;
}) {
  return (
    <section className="mb-6 rounded-3xl border-2 border-terracotta/30 bg-terracotta/[0.04] p-5 md:p-6">
      <div className="mb-4 flex flex-wrap items-baseline justify-between gap-3">
        <div>
          <p
            className="text-[11px] font-semibold uppercase tracking-[0.18em]"
            style={{ color: "#C94B2A" }}
          >
            Real photos · typical offspring
          </p>
          <h3
            className="mt-1 leading-tight text-dark"
            style={{
              fontFamily: "var(--font-playfair, Georgia, serif)",
              fontWeight: 800,
              fontSize: "1.25rem",
            }}
          >
            What a {breedA} × {breedB} cross looks like
          </h3>
        </div>
        <p className="max-w-md text-[12px] text-dark-muted leading-relaxed">
          Licensed photographs of real dogs that are actual mixes of these
          two breeds. Not generated. Not stylized. Every dog below is a
          different individual.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        {mixPhotos.slice(0, 4).map((p, i) => (
          <figure key={`${p.url}-${i}`} className="overflow-hidden rounded-2xl">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={p.url}
              alt={p.caption}
              className="aspect-square w-full object-cover transition-transform hover:scale-[1.03]"
              loading="lazy"
            />
            <figcaption className="mt-1.5 line-clamp-2 text-[10px] leading-snug text-dark-muted">
              {p.caption}
            </figcaption>
          </figure>
        ))}
      </div>

      <p className="mt-5 rounded-2xl border border-terracotta/25 bg-surface/80 px-4 py-3 text-[12px] leading-relaxed text-dark">
        <strong>Your puppies will not look exactly like these.</strong>{" "}
        Mendelian inheritance produces enormous variation across a single
        litter — two puppies from the same mating can look very different
        from each other. Treat these as the range of what&apos;s plausible,
        not a portrait of what will happen.
      </p>
    </section>
  );
}

/* ─── Subcomponents ──────────────────────────────────────────────────── */

function Dots() {
  return (
    <span aria-hidden="true" className="inline-flex gap-1">
      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-terracotta [animation-delay:0ms]" />
      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-terracotta [animation-delay:150ms]" />
      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-terracotta [animation-delay:300ms]" />
    </span>
  );
}

/**
 * Lightweight markdown renderer for the streamed Claude response.
 * Supports headings, bold, lists, and paragraphs — enough for the
 * prompt's output shape. We don't pull in a full markdown lib to keep
 * the bundle slim; if we need more we'd swap in `react-markdown`.
 */
function MarkdownPreview({ text }: { text: string }) {
  const blocks = text.split(/\n\n+/).filter((b) => b.trim().length > 0);
  return (
    <div className="space-y-4 text-[15px] leading-relaxed text-dark">
      {blocks.map((block, i) => {
        // Heading line ("**Heading**" on its own)
        const headingMatch = /^\*\*(.+?)\*\*\s*$/.exec(block.trim());
        if (headingMatch) {
          return (
            <h3
              key={i}
              className="mt-2 leading-tight text-dark"
              style={{
                fontFamily: "var(--font-playfair, Georgia, serif)",
                fontWeight: 800,
                fontSize: "1.25rem",
              }}
            >
              {headingMatch[1]}
            </h3>
          );
        }
        // List block
        const lines = block.split(/\n/);
        const isList = lines.every((l) => /^\s*[-*]\s+/.test(l));
        if (isList) {
          return (
            <ul key={i} className="list-disc pl-5 space-y-1.5 marker:text-terracotta">
              {lines.map((l, j) => (
                <li key={j}>{renderInline(l.replace(/^\s*[-*]\s+/, ""))}</li>
              ))}
            </ul>
          );
        }
        // Plain paragraph
        return (
          <p key={i} className="whitespace-pre-wrap">
            {renderInline(block)}
          </p>
        );
      })}
    </div>
  );
}

/** Inline-bold renderer. Splits on `**…**` only. */
function renderInline(text: string): React.ReactNode[] {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    const boldMatch = /^\*\*(.+?)\*\*$/.exec(part);
    if (boldMatch) {
      return (
        <strong key={i} className="font-semibold">
          {boldMatch[1]}
        </strong>
      );
    }
    return <span key={i}>{part}</span>;
  });
}
