"use client";

import { useEffect, useRef, useState } from "react";

import { useToast } from "@/components/toast/ToastProvider";

interface OffspringProfilePanelProps {
  petAId: string;
  petBId: string;
  petAName: string;
  petBName: string;
}

/**
 * The holistic offspring-profile prediction panel — coat colors, size,
 * temperament, appearance, training notes. Streams from
 * /api/predict/offspring. Renders progressively as Claude generates.
 */
export function OffspringProfilePanel({
  petAId,
  petBId,
  petAName,
  petBName,
}: OffspringProfilePanelProps) {
  const toast = useToast();
  const [text, setText] = useState("");
  const [streaming, setStreaming] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const startedRef = useRef(false);

  useEffect(() => {
    // Effects run twice in dev under React Strict Mode; gate via ref.
    if (startedRef.current) return;
    startedRef.current = true;
    void runPrediction();

    async function runPrediction() {
      try {
        const r = await fetch("/api/predict/offspring", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ petAId, petBId }),
        });
        if (!r.ok || !r.body) {
          const data = await r.json().catch(() => ({}));
          throw new Error(
            (data as { error?: string }).error ?? "Prediction request failed",
          );
        }
        const reader = r.body.getReader();
        const decoder = new TextDecoder();
        let acc = "";
        // eslint-disable-next-line no-constant-condition
        while (true) {
          const { value, done } = await reader.read();
          if (done) break;
          acc += decoder.decode(value, { stream: true });
          setText(acc);
        }
      } catch (err) {
        const message = (err as Error).message;
        setError(message);
        toast.error("Couldn't generate the offspring profile", message);
      } finally {
        setStreaming(false);
      }
    }
  }, [petAId, petBId, toast]);

  return (
    <section className="mt-12">
      <header className="mb-5 max-w-2xl">
        <p className="eyebrow">AI offspring profile</p>
        <h2
          className="mt-3 leading-tight text-dark"
          style={{
            fontFamily: "var(--font-playfair, Georgia, serif)",
            fontWeight: 900,
            fontSize: "clamp(1.75rem, 4vw, 2.5rem)",
          }}
        >
          What the litter will likely look like
        </h2>
        <p className="mt-2 text-sm text-dark-muted leading-relaxed">
          A holistic prediction of {petAName} × {petBName}&apos;s puppies — coat,
          size, temperament, and any health considerations from the parents&apos;
          DNA records. Generated by an AI model grounded in both parents&apos;
          breed reference + trait data; not a clinical recommendation.
        </p>
      </header>

      <article className="rounded-3xl border border-sand bg-surface p-6 shadow-card md:p-8">
        {streaming && text.length === 0 ? (
          <div className="flex items-center gap-2 text-sm text-dark-muted">
            <Dots />
            <span>Analyzing {petAName} and {petBName}&apos;s genetic profiles…</span>
          </div>
        ) : error ? (
          <p className="text-sm text-dark-muted">
            We couldn&apos;t generate the prediction right now. {error}
          </p>
        ) : (
          <MarkdownPreview text={text} />
        )}
        {streaming && text.length > 0 && (
          <div className="mt-3 flex items-center gap-2 text-[11px] text-dark-muted">
            <Dots />
            <span>Still writing…</span>
          </div>
        )}
      </article>
    </section>
  );
}

/* ─── Subcomponents ──────────────────────────────────────────────────── */

function Dots() {
  return (
    <span aria-hidden="true" className="inline-flex gap-1">
      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-terracotta [animation-delay:0ms]" />
      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-terracotta [animation-delay:150ms]" />
      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-terracotta [animation-delay:300ms]" />
    </span>
  );
}

/**
 * Lightweight markdown renderer for the streamed Claude response.
 * Supports headings, bold, lists, and paragraphs — enough for the
 * prompt's output shape. We don't pull in a full markdown lib to keep
 * the bundle slim; if we need more we'd swap in `react-markdown`.
 */
function MarkdownPreview({ text }: { text: string }) {
  const blocks = text.split(/\n\n+/).filter((b) => b.trim().length > 0);
  return (
    <div className="space-y-4 text-[15px] leading-relaxed text-dark">
      {blocks.map((block, i) => {
        // Heading line ("**Heading**" on its own)
        const headingMatch = /^\*\*(.+?)\*\*\s*$/.exec(block.trim());
        if (headingMatch) {
          return (
            <h3
              key={i}
              className="mt-2 leading-tight text-dark"
              style={{
                fontFamily: "var(--font-playfair, Georgia, serif)",
                fontWeight: 800,
                fontSize: "1.25rem",
              }}
            >
              {headingMatch[1]}
            </h3>
          );
        }
        // List block
        const lines = block.split(/\n/);
        const isList = lines.every((l) => /^\s*[-*]\s+/.test(l));
        if (isList) {
          return (
            <ul key={i} className="list-disc pl-5 space-y-1.5 marker:text-terracotta">
              {lines.map((l, j) => (
                <li key={j}>{renderInline(l.replace(/^\s*[-*]\s+/, ""))}</li>
              ))}
            </ul>
          );
        }
        // Plain paragraph
        return (
          <p key={i} className="whitespace-pre-wrap">
            {renderInline(block)}
          </p>
        );
      })}
    </div>
  );
}

/** Inline-bold renderer. Splits on `**…**` only. */
function renderInline(text: string): React.ReactNode[] {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    const boldMatch = /^\*\*(.+?)\*\*$/.exec(part);
    if (boldMatch) {
      return (
        <strong key={i} className="font-semibold">
          {boldMatch[1]}
        </strong>
      );
    }
    return <span key={i}>{part}</span>;
  });
}
